[Rectangle]
long_side=100
short_side=70
symmetry=180
[LShape]
; 中西
long_side=150
short_side=100
long_pro=40
short_pro=40
symmetry=360
; 今井
; long_side=112.5
; short_side=75
; long_pro=30
; short_pro=30
; symmetry=360
[Triangle]
edge1=150
edge2=150
edge3=150
symmetry=120
[TShape]
long_side=150
short_side=120
long_pro=40
short_pro=40
symmetry=360
